### ISSUE TITLE
What's the guidelines and architecture for this project?

### ISSUE THREAD

**Issue by yamin8000** [moeindev/KotlinPersianUtils#21]
Hi
I want to help with this project, but there seems to be no initial structure for this project. If original developers would be kind enough to complete the initial structure of this code so I can help too in my spare time.
@moeindev
What I mean by structure/architecture is how classes should be named, how packages should be named, showing a template pull request, requirements for a valid pull request, which test frameworks should be used, etc.

**Comment by moeindev** [comment]
Hello, I no longer contribute to this project please ask @ali-master about the details
